# Generated by Django 2.1.5 on 2019-02-02 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('presenter', models.CharField(blank=True, max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 2, 2, 0, 14, 47, 427344, tzinfo=utc))),
                ('location', models.CharField(blank=True, max_length=256)),
                ('coordinator', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
